[package]
name = "yaldabaranth"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.100"
hecs = "0.10.5"
macroquad = { version = "0.4.14", features = ["backtrace"] }
rayon = "1.11.0"
